/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examen.pkg1_carlosvarela;

import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author carlo
 */
public class Biblioteca extends javax.swing.JFrame {

    static boolean Adminhabilitado = false;
    static boolean Usuariohabilitado = false;
    static int Elusuario_numero;
    static String nombreAdmin = ">:v", contraseñaAdmin = "69";
    /**
     * Creates new form Biblioteca
     */
    public Biblioteca() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Radio_botones = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jp_agregarUsuario = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        dc_Fecha = new com.toedter.calendar.JDateChooser();
        tf_NombreUsuario = new javax.swing.JTextField();
        tf_NombreCompleto = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tf_correo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tf_telefono = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tf_contraseña = new javax.swing.JTextField();
        jb_guardarUser = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        cb_accion = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        cb_fantasia = new javax.swing.JCheckBox();
        cb_romance = new javax.swing.JCheckBox();
        cb_historia = new javax.swing.JCheckBox();
        jp_Login = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tf_NombreuserLogin = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        tf_contraseñaLogin = new javax.swing.JTextField();
        jb_iniciarsesion = new javax.swing.JButton();
        jp_AgregarLibros = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        tf_titulo = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta_descripcion = new javax.swing.JTextArea();
        jLabel15 = new javax.swing.JLabel();
        tf_puntaje = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        tf_copias = new javax.swing.JTextField();
        rb_romance = new javax.swing.JRadioButton();
        rb_historia = new javax.swing.JRadioButton();
        rb_accion = new javax.swing.JRadioButton();
        rb_fantasia = new javax.swing.JRadioButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        tf_valor = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        tf_edicion = new javax.swing.JTextField();
        dc_FechaLibro = new com.toedter.calendar.JDateChooser();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        tf_autor = new javax.swing.JTextField();
        fb_guardarLibro = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        tf_SolicitudNombre = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        ta_DescripcionAmigo = new javax.swing.JTextArea();
        jb_MandarSolicitud = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        tf_NombreLibro = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        ta_DescripcionTodosLibros = new javax.swing.JTextArea();
        jLabel32 = new javax.swing.JLabel();
        jb_AgregarLibro = new javax.swing.JButton();
        jb_ActualizarLista = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        ta_Librosfav = new javax.swing.JTextArea();
        jb_BuscarLibrosFav = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        tf_quierobuscar = new javax.swing.JTextField();
        jb_BuscarLibro = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ta_DescripcionDeUnLibro = new javax.swing.JTextArea();
        jPanel5 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jb_cerrarSesion = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        ta_Listadeacciones = new javax.swing.JTextArea();
        jb_ActualizarAcciones = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        ta_libroseliminar = new javax.swing.JTextArea();
        jLabel35 = new javax.swing.JLabel();
        tf_EliminarLibro = new javax.swing.JTextField();
        jb_Eliminar = new javax.swing.JButton();
        jb_ActualizarEliminarLista = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Lucida Calligraphy", 0, 24)); // NOI18N
        jLabel1.setText("Agregar Usuario ");

        jLabel2.setText("Nombre Completo:");

        jLabel3.setText("Nombre:");

        jLabel4.setText("Fecha de nacimiento: ");

        tf_NombreCompleto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_NombreCompletoActionPerformed(evt);
            }
        });

        jLabel5.setText("Correo electronico: ");

        jLabel6.setText("Numero telefonico: ");

        jLabel7.setText("Contraseña:");

        jb_guardarUser.setText("Guardar");
        jb_guardarUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_guardarUserMouseClicked(evt);
            }
        });

        jLabel8.setText("Genero favorito: ");

        cb_accion.setText("Acción");

        jCheckBox2.setText("Acción");

        cb_fantasia.setText("fantasia");

        cb_romance.setText("Romance");

        cb_historia.setText("Historia");

        javax.swing.GroupLayout jp_agregarUsuarioLayout = new javax.swing.GroupLayout(jp_agregarUsuario);
        jp_agregarUsuario.setLayout(jp_agregarUsuarioLayout);
        jp_agregarUsuarioLayout.setHorizontalGroup(
            jp_agregarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_agregarUsuarioLayout.createSequentialGroup()
                .addGroup(jp_agregarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_agregarUsuarioLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dc_Fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jp_agregarUsuarioLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(tf_contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jp_agregarUsuarioLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jp_agregarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jp_agregarUsuarioLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(tf_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jp_agregarUsuarioLayout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tf_correo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jp_agregarUsuarioLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jp_agregarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jp_agregarUsuarioLayout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24)
                                .addComponent(tf_NombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jp_agregarUsuarioLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(tf_NombreCompleto, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jp_agregarUsuarioLayout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jp_agregarUsuarioLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jp_agregarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jb_guardarUser, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jp_agregarUsuarioLayout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addGroup(jp_agregarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cb_accion)
                                    .addComponent(jCheckBox2))
                                .addGap(3, 3, 3)
                                .addComponent(cb_fantasia)))
                        .addGap(5, 5, 5)
                        .addComponent(cb_romance)
                        .addGap(1, 1, 1)
                        .addComponent(cb_historia)))
                .addContainerGap(92, Short.MAX_VALUE))
        );
        jp_agregarUsuarioLayout.setVerticalGroup(
            jp_agregarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_agregarUsuarioLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jp_agregarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tf_NombreCompleto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jp_agregarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tf_NombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jp_agregarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dc_Fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(20, 20, 20)
                .addGroup(jp_agregarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_correo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jp_agregarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(10, 10, 10)
                .addGroup(jp_agregarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jp_agregarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_accion)
                    .addComponent(jCheckBox2)
                    .addComponent(cb_fantasia)
                    .addComponent(cb_romance)
                    .addComponent(cb_historia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jb_guardarUser, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Agregar usuario ", jp_agregarUsuario);

        jLabel9.setFont(new java.awt.Font("Lucida Calligraphy", 0, 36)); // NOI18N
        jLabel9.setText("LogIn");

        jLabel10.setText("Ingresar Nombre de usuario: ");

        jLabel11.setText("Contraseña: ");

        jb_iniciarsesion.setText("Iniciar Sesion");
        jb_iniciarsesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_iniciarsesionMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jp_LoginLayout = new javax.swing.GroupLayout(jp_Login);
        jp_Login.setLayout(jp_LoginLayout);
        jp_LoginLayout.setHorizontalGroup(
            jp_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_LoginLayout.createSequentialGroup()
                .addGroup(jp_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_LoginLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jp_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jp_LoginLayout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf_NombreuserLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jp_LoginLayout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tf_contraseñaLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jp_LoginLayout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jp_LoginLayout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(jb_iniciarsesion, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(158, Short.MAX_VALUE))
        );
        jp_LoginLayout.setVerticalGroup(
            jp_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_LoginLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jp_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_NombreuserLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jp_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(tf_contraseñaLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jb_iniciarsesion, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(318, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Iniciar Sesion", jp_Login);

        jLabel12.setFont(new java.awt.Font("Lucida Calligraphy", 0, 36)); // NOI18N
        jLabel12.setText("Agregar Libros");

        jLabel13.setText("Título: ");

        jLabel14.setText("Descripcion: ");

        ta_descripcion.setColumns(20);
        ta_descripcion.setRows(5);
        jScrollPane1.setViewportView(ta_descripcion);

        jLabel15.setText("Puntaje: ");

        jLabel16.setText("Copias: ");

        Radio_botones.add(rb_romance);
        rb_romance.setText("Romance");

        Radio_botones.add(rb_historia);
        rb_historia.setText("Historia");

        Radio_botones.add(rb_accion);
        rb_accion.setText("Acción");

        Radio_botones.add(rb_fantasia);
        rb_fantasia.setText("Fantasia");

        jLabel17.setText("Genero: ");

        jLabel18.setText("Valor: ");

        tf_valor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_valorActionPerformed(evt);
            }
        });

        jLabel19.setText("Edicion:");

        jLabel20.setText("Fecha de publicación: ");

        jLabel21.setText("Autor:");

        fb_guardarLibro.setText("Guardar");
        fb_guardarLibro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fb_guardarLibroMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jp_AgregarLibrosLayout = new javax.swing.GroupLayout(jp_AgregarLibros);
        jp_AgregarLibros.setLayout(jp_AgregarLibrosLayout);
        jp_AgregarLibrosLayout.setHorizontalGroup(
            jp_AgregarLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_AgregarLibrosLayout.createSequentialGroup()
                .addGroup(jp_AgregarLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_AgregarLibrosLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(jp_AgregarLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)
                            .addGroup(jp_AgregarLibrosLayout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jp_AgregarLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tf_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jp_AgregarLibrosLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(jp_AgregarLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jp_AgregarLibrosLayout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addGap(18, 18, 18)
                                .addComponent(tf_autor, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jp_AgregarLibrosLayout.createSequentialGroup()
                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(tf_edicion, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jp_AgregarLibrosLayout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf_valor, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jp_AgregarLibrosLayout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rb_romance)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rb_historia)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rb_accion)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rb_fantasia))
                            .addGroup(jp_AgregarLibrosLayout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf_puntaje, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel16)
                                .addGap(18, 18, 18)
                                .addComponent(tf_copias, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jp_AgregarLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(fb_guardarLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jp_AgregarLibrosLayout.createSequentialGroup()
                                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(dc_FechaLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        jp_AgregarLibrosLayout.setVerticalGroup(
            jp_AgregarLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_AgregarLibrosLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jp_AgregarLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tf_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel14)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(jp_AgregarLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_AgregarLibrosLayout.createSequentialGroup()
                        .addGroup(jp_AgregarLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(tf_puntaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16)
                            .addComponent(tf_copias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addComponent(jLabel17))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_AgregarLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rb_romance)
                        .addComponent(rb_historia)
                        .addComponent(rb_accion)
                        .addComponent(rb_fantasia)))
                .addGap(18, 18, 18)
                .addGroup(jp_AgregarLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(tf_valor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jp_AgregarLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jp_AgregarLibrosLayout.createSequentialGroup()
                        .addGroup(jp_AgregarLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(tf_edicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel20))
                    .addComponent(dc_FechaLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jp_AgregarLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_autor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addGap(30, 30, 30)
                .addComponent(fb_guardarLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        jTabbedPane1.addTab("Agregar Libros", jp_AgregarLibros);

        jLabel28.setFont(new java.awt.Font("Lucida Calligraphy", 0, 36)); // NOI18N
        jLabel28.setText("Agregar Amigos");

        jLabel29.setText("Ingrese nombre:");

        jLabel30.setText("Descripcion: ");

        ta_DescripcionAmigo.setColumns(20);
        ta_DescripcionAmigo.setRows(5);
        jScrollPane3.setViewportView(ta_DescripcionAmigo);

        jb_MandarSolicitud.setText("Mandar");
        jb_MandarSolicitud.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_MandarSolicitudMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tf_SolicitudNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jb_MandarSolicitud, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel30)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_SolicitudNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_MandarSolicitud, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel30)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(113, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Agregar Amigos", jPanel3);

        jLabel22.setFont(new java.awt.Font("Lucida Calligraphy", 0, 18)); // NOI18N
        jLabel22.setText("Agregar Libros a mi lista");

        jLabel26.setText("Nombre del Libro :");

        ta_DescripcionTodosLibros.setColumns(20);
        ta_DescripcionTodosLibros.setRows(5);
        jScrollPane5.setViewportView(ta_DescripcionTodosLibros);

        jLabel32.setText("Lista de libros");

        jb_AgregarLibro.setText("Agregar");
        jb_AgregarLibro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_AgregarLibroMouseClicked(evt);
            }
        });

        jb_ActualizarLista.setText("Actualizar Lista");
        jb_ActualizarLista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_ActualizarListaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(jLabel22))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addComponent(jLabel32))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_NombreLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jb_AgregarLibro))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(jb_ActualizarLista)))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(tf_NombreLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_AgregarLibro))
                .addGap(24, 24, 24)
                .addComponent(jLabel32)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jb_ActualizarLista)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Mi Lista de libros", jPanel1);

        jLabel31.setFont(new java.awt.Font("Lucida Calligraphy", 0, 18)); // NOI18N
        jLabel31.setText("Algunos libros que talves te interesen... ");

        ta_Librosfav.setColumns(20);
        ta_Librosfav.setRows(5);
        jScrollPane4.setViewportView(ta_Librosfav);

        jb_BuscarLibrosFav.setText("Buscar");
        jb_BuscarLibrosFav.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_BuscarLibrosFavMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addComponent(jb_BuscarLibrosFav, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jb_BuscarLibrosFav, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(85, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Lista de libros favoritos", jPanel4);

        jLabel23.setFont(new java.awt.Font("Lucida Calligraphy", 0, 18)); // NOI18N
        jLabel23.setText("¿Que libro desea buscar?...");

        jLabel24.setText("Ingrese nombre o numero del libro: ");

        jb_BuscarLibro.setText("Buscar");
        jb_BuscarLibro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_BuscarLibroMouseClicked(evt);
            }
        });

        jLabel25.setText("Descripción: ");

        ta_DescripcionDeUnLibro.setColumns(20);
        ta_DescripcionDeUnLibro.setRows(5);
        jScrollPane2.setViewportView(ta_DescripcionDeUnLibro);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel24)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_quierobuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel25)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(jb_BuscarLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(107, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_quierobuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jb_BuscarLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel25)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Buscar Libros", jPanel2);

        jLabel27.setFont(new java.awt.Font("Lucida Calligraphy", 0, 18)); // NOI18N
        jLabel27.setText("¿Seguro que deseas cerrar sesion?");

        jb_cerrarSesion.setText("Si, quiero cerrar sesion");
        jb_cerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_cerrarSesionMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(jb_cerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jb_cerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(226, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Cerrar Sesion", jPanel5);

        jLabel33.setFont(new java.awt.Font("Lucida Calligraphy", 0, 18)); // NOI18N
        jLabel33.setText("Acciones que se han hecho... ");

        ta_Listadeacciones.setColumns(20);
        ta_Listadeacciones.setRows(5);
        jScrollPane6.setViewportView(ta_Listadeacciones);

        jb_ActualizarAcciones.setText("Actualizar Lista");
        jb_ActualizarAcciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_ActualizarAccionesMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(86, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addComponent(jb_ActualizarAcciones, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jb_ActualizarAcciones)
                .addContainerGap(78, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Lista de acciones", jPanel6);

        jLabel34.setFont(new java.awt.Font("Lucida Calligraphy", 0, 24)); // NOI18N
        jLabel34.setText("Eliminar...");

        ta_libroseliminar.setColumns(20);
        ta_libroseliminar.setRows(5);
        jScrollPane7.setViewportView(ta_libroseliminar);

        jLabel35.setText("Ingresar Nombre:");

        jb_Eliminar.setText("Eliminar");
        jb_Eliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_EliminarMouseClicked(evt);
            }
        });

        jb_ActualizarEliminarLista.setText("Actualizar");
        jb_ActualizarEliminarLista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_ActualizarEliminarListaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel35)
                        .addGap(18, 18, 18)
                        .addComponent(tf_EliminarLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jb_Eliminar))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addComponent(jb_ActualizarEliminarLista)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_EliminarLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel35)
                    .addComponent(jb_Eliminar))
                .addGap(48, 48, 48)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jb_ActualizarEliminarLista)
                .addContainerGap(85, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Eliminar ", jPanel7);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf_NombreCompletoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_NombreCompletoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_NombreCompletoActionPerformed

    
    ///// Agtegar Nuevos usuarios!!!!!! 
    private void jb_guardarUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_guardarUserMouseClicked
        String nombre, nombre_usuario, contraseña, correo, genero_favorito;
        Date fecha;
        int telefono;
        if (Adminhabilitado==true) {
            JOptionPane.showMessageDialog(this, "Usuario registrado");
            try {
            nombre = tf_NombreCompleto.getText();
            nombre_usuario = tf_NombreUsuario.getText();
            fecha = dc_Fecha.getDate();
            correo = tf_correo.getText();
            contraseña = tf_contraseña.getText();
            telefono  = Integer.parseInt(tf_telefono.getText());
            if (cb_accion.isSelected()) {
                genero_favorito = "Acción";
            }else if (cb_fantasia.isSelected()) {
                genero_favorito = "Fantasia";
            }else if (cb_historia.isSelected()) {
                genero_favorito = "Historia";
            }else if (cb_romance.isSelected()) {
                genero_favorito = "Romance";
            }else {
                genero_favorito = "";
            }
            usuarios.add(new Usuario(nombre_usuario, contraseña, correo, nombre, genero_favorito, fecha, telefono));
            Acciones.add("Se ingreso usuario. ");
            //Reiniciando variables
            tf_telefono.setText("");
            tf_NombreCompleto.setText("");
            tf_NombreUsuario.setText("");
            dc_Fecha.setDate(new Date());
            tf_correo.setText("");
            tf_contraseña.setText("");
            cb_accion.setSelected(false);
            cb_fantasia.setSelected(false);
            cb_historia.setSelected(false);
            cb_romance.setSelected(false);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "No se pudieron guardar los datos, ingrese de nuevo, correctamente");
            }
        }else if (Usuariohabilitado==true){
                JOptionPane.showMessageDialog(this, "No puede registrar usuarios, necesita iniciar sesion con el\n"
                        + "Usuario administrador");
        }else{
            JOptionPane.showMessageDialog(this, "Necesita inicia sesion con el admin");
            tf_telefono.setText("");
            tf_NombreCompleto.setText("");
            tf_NombreUsuario.setText("");
            dc_Fecha.setDate(new Date());
            tf_correo.setText("");
            tf_contraseña.setText("");
            cb_accion.setSelected(false);
            cb_fantasia.setSelected(false);
            cb_historia.setSelected(false);
            cb_romance.setSelected(false);
        }
    }//GEN-LAST:event_jb_guardarUserMouseClicked

    //Inicio de sesion
    private void jb_iniciarsesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_iniciarsesionMouseClicked
        String nombre, contraseña;
        if (Adminhabilitado==false&&Usuariohabilitado==false) {
            try {
            nombre = tf_NombreuserLogin.getText();
            contraseña = tf_contraseñaLogin.getText();
            //Para admin
            if (nombre.equals(nombreAdmin)&&contraseña.equals(contraseñaAdmin)) {
                JOptionPane.showMessageDialog(this, "Bienvenido Admin");
                tf_NombreuserLogin.setText("");
                tf_contraseñaLogin.setText("");
                Adminhabilitado = true;
                Acciones.add("Admin inicio sesion");
            //Para otros usuarios
            }else if (inicio(nombre,contraseña)==true){
                JOptionPane.showMessageDialog(this, "Bienvenido "+nombre);
                tf_NombreuserLogin.setText("");
                tf_contraseñaLogin.setText("");
                Acciones.add("Usuario Ingreso sesion");
            }else{
                JOptionPane.showMessageDialog(this, "No inicio sesion, ingrese de nuevo");
                tf_NombreuserLogin.setText("");
                tf_contraseñaLogin.setText("");
            }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "No se inicio, ingrese de nuevo correctamente los datos");
            }
        }else{
            
            JOptionPane.showMessageDialog(this,"Tiene sesion iniciada");
        }
    }//GEN-LAST:event_jb_iniciarsesionMouseClicked

    private void tf_valorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_valorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_valorActionPerformed

    
    //Agregando libros
    private void fb_guardarLibroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fb_guardarLibroMouseClicked
        // TODO add your handling code here:
        String titulo, descripcion, genero = "", edicion ,autor;
        Date fecha_publicacion;
        int num_copias, valor, puntaje;
        if (Adminhabilitado==true) {
            try {
                puntaje = Integer.parseInt(tf_puntaje.getText());
                while(puntaje<0||puntaje>5){
                    puntaje = Integer.parseInt(JOptionPane.showInputDialog(this, "No se admite ese valor, ingrese otro: "));
                }
                titulo = tf_titulo.getText();
                descripcion = ta_descripcion.getText();
                num_copias = Integer.parseInt(tf_copias.getText());
                if (rb_accion.isSelected()) {
                    genero = "Acción";
                }else if (rb_fantasia.isSelected()) {
                    genero = "Fantasia";
                }else if (rb_historia.isSelected()) {
                    genero = "Historia";
                }else if (rb_romance.isSelected()) {
                    genero = "Romance";
                }
                valor = Integer.parseInt(tf_valor.getText());
                edicion = tf_edicion.getText();
                autor = tf_autor.getText();
                fecha_publicacion = dc_FechaLibro.getDate();
                
                libros.add(new Libro(titulo, descripcion, genero, autor, edicion, fecha_publicacion, num_copias, puntaje));
                
                //Limpiando variables
                tf_titulo.setText("");
                tf_puntaje.setText("");
                ta_descripcion.setText("");
                tf_copias.setText("");
                rb_accion.setSelected(false);
                rb_fantasia.setSelected(false);
                rb_historia.setSelected(false);
                rb_romance.setSelected(false);
                
                JOptionPane.showMessageDialog(this, "Libro agregado con exito! ");
                Acciones.add("Libro agregado");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Hubo un problema, ingrese de nuevo los datos");
            }
        }else{
            JOptionPane.showMessageDialog(this, "No puedes agregar libros, no eres admin");
            tf_titulo.setText("");
            tf_puntaje.setText("");
            ta_descripcion.setText("");
            tf_copias.setText("");
            rb_accion.setSelected(false);
            rb_fantasia.setSelected(false);
            rb_historia.setSelected(false);
            rb_romance.setSelected(false);
        }
    }//GEN-LAST:event_fb_guardarLibroMouseClicked

    //Buscar Libros
    private void jb_BuscarLibroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_BuscarLibroMouseClicked
        String buscar;
        if (Usuariohabilitado==true){
            if (libros.size()>0) {
                buscar = tf_quierobuscar.getText();
                for (int i = 0; i < libros.size(); i++) {
                    if (libros.get(i).getTitulo().equalsIgnoreCase(buscar)) {
                        ta_DescripcionDeUnLibro.setText("Titulo: "+libros.get(i).getTitulo()
                        +"\nAutor: "+libros.get(i).getAutor()
                        +"\nDescripcion: "+libros.get(i).getPuntaje()
                        +"\nGenero: "+libros.get(i).getGenero()
                        +"\nEdición: "+libros.get(i).getEdicion()
                        +"\nAño de publicacion: "+libros.get(i).getFecha_edicion()
                        +"\nNumero de copias: "+libros.get(i).getNum_copias());
                    }
                }
                Acciones.add("Se busco un libro");
            }else{
                JOptionPane.showMessageDialog(this, "No hay libros para mostrar");
            }
        }else{
                JOptionPane.showMessageDialog(this, "Necesitas iniciar sesion con otro usuario");
        }
    }//GEN-LAST:event_jb_BuscarLibroMouseClicked

    //Cerrar Sesion
    private void jb_cerrarSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_cerrarSesionMouseClicked
        if (Adminhabilitado==false&&Usuariohabilitado==false) {
            JOptionPane.showMessageDialog(this, "No tiene alguna sesion iniciada");
        }else{
            Adminhabilitado = false;
            Usuariohabilitado = false;
            Elusuario_numero = -1;
            tf_SolicitudNombre.setText("");
            ta_DescripcionAmigo.setText("");
            JOptionPane.showMessageDialog(this, "Adios :)");
            Acciones.add("Sesion cerrada");
        }
    }//GEN-LAST:event_jb_cerrarSesionMouseClicked

    //Manda solicitudes
    private void jb_MandarSolicitudMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_MandarSolicitudMouseClicked
        String nombre;
        boolean correcto = false;
        if (Usuariohabilitado==true) {
            nombre  = tf_SolicitudNombre.getText();
            for (int i = 0; i < usuarios.size(); i++) {
                if (usuarios.get(i).getNombreUsuario().equalsIgnoreCase(nombre)&&nombre.equals(usuarios.get(Elusuario_numero).getNombreUsuario())==false) {
                    //Le añade la solicitud al usuario
                    usuarios.get(i).setMisSolicitudes(usuarios.get(Elusuario_numero).getNombre_completo());
                    correcto = true;
                    ta_DescripcionAmigo.setText(usuarios.get(i).toString());
                }
            }
            if (correcto==false) {
                JOptionPane.showMessageDialog(this, "Ingrese bien el nombre del usuario");
            }else{
                Acciones.add("Se mando solicitud");
                JOptionPane.showMessageDialog(this, "Solicitud ingresada exitosamente");
            }
        }else if (Adminhabilitado==true){
            JOptionPane.showMessageDialog(this, "Tiene que iniciar secion con otro usuario");
            ta_DescripcionAmigo.setText("");
        }else{
            JOptionPane.showMessageDialog(this, "Tiene que iniciar sesion");
        }
    }//GEN-LAST:event_jb_MandarSolicitudMouseClicked

    
    private void jb_BuscarLibrosFavMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_BuscarLibrosFavMouseClicked
        String acum = "";
        if (Adminhabilitado==true) {
            JOptionPane.showMessageDialog(this, "Inicie sesion con otro usuario");
        }else if (Usuariohabilitado==true){
            Acciones.add("Se busco todos los libros");
            for (int i = 0; i < libros.size(); i++) {
                if (libros.get(i).getGenero().equals(usuarios.get(Elusuario_numero).getGenero_fav())) {
                    acum+=libros.get(i).toString()+"\n";
                    
                }
            }
            ta_Librosfav.setText(acum);
        }else{
            JOptionPane.showMessageDialog(this, "Inicie sesion con usuario");
        }
    }//GEN-LAST:event_jb_BuscarLibrosFavMouseClicked

    private void jb_AgregarLibroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_AgregarLibroMouseClicked
        String nombre;
        boolean correcto = false;
        if (Usuariohabilitado==true) {
            nombre = tf_NombreLibro.getText();
            for (int i = 0; i < libros.size(); i++) {
                if (libros.get(i).getTitulo().equals(nombre)) {
                    usuarios.get(Elusuario_numero).setMislibros(libros.get(i));
                }
            }
            if (correcto==true) {
                JOptionPane.showMessageDialog(this, "Se agrego un libro exitosamente");
                Acciones.add("Se agrego un libro");
            }else{
                JOptionPane.showMessageDialog(this, "No se agrego libro, ingrese correctamente el nombre");
            }
        }else if (Adminhabilitado==true){
            JOptionPane.showMessageDialog(this, "Inicie sesion con usuario");
        }else{
            JOptionPane.showMessageDialog(this, "Inicie sesion con algun usuario");
        }
    }//GEN-LAST:event_jb_AgregarLibroMouseClicked

    private void jb_ActualizarListaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_ActualizarListaMouseClicked
        // TODO add your handling code here:
        String acum = "";
        for (int i = 0; i < libros.size(); i++) {
            acum+=libros.get(i).toString()+"\n";
        }
        ta_DescripcionTodosLibros.setText(acum);
        Acciones.add("Se actualizo la lista de libros");
    }//GEN-LAST:event_jb_ActualizarListaMouseClicked

    private void jb_ActualizarAccionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_ActualizarAccionesMouseClicked
        String acum = "";
        for (int i = 0; i < Acciones.size(); i++) {
           acum+=Acciones.get(i).toString()+"\n";
        }
        ta_Listadeacciones.setText(acum);
    }//GEN-LAST:event_jb_ActualizarAccionesMouseClicked

    private void jb_EliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_EliminarMouseClicked
        String nombre;
        if (Adminhabilitado==true) {
            nombre = ta_libroseliminar.getText();
            for (int i = 0; i < libros.size(); i++) {
                if (libros.get(i).getTitulo().equals(nombre)) {
                libros.remove(i);
                }
            }
        }else if (Usuariohabilitado==true){
            JOptionPane.showMessageDialog(this, "No puede usar esta funcion");
        }else{
            JOptionPane.showMessageDialog(this, "Ingrese sesion con adm");    
        }
    }//GEN-LAST:event_jb_EliminarMouseClicked

    private void jb_ActualizarEliminarListaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_ActualizarEliminarListaMouseClicked
        String acum = "";
        for (int i = 0; i < libros.size(); i++) {
           acum+=libros.get(i).toString()+"\n";
        }
        ta_libroseliminar.setText(acum);
    }//GEN-LAST:event_jb_ActualizarEliminarListaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Biblioteca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Biblioteca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Biblioteca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Biblioteca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Biblioteca().setVisible(true);
            }
        });
    }

    //Inicio de sesion
    public static boolean inicio(String nombre, String contraseña){
        if (Adminhabilitado==false&&Usuariohabilitado==false) {
            for (int i = 0; i < usuarios.size(); i++) {
                if (usuarios.get(i).getNombreUsuario().equals(nombre)&&usuarios.get(i).getContraseña().equals(contraseña)) {
                    Usuariohabilitado = true;
                    Elusuario_numero = i;
                    return true;
                }
            }
        }else{
            return false;
        }
        return false;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup Radio_botones;
    private javax.swing.JCheckBox cb_accion;
    private javax.swing.JCheckBox cb_fantasia;
    private javax.swing.JCheckBox cb_historia;
    private javax.swing.JCheckBox cb_romance;
    private com.toedter.calendar.JDateChooser dc_Fecha;
    private com.toedter.calendar.JDateChooser dc_FechaLibro;
    private javax.swing.JButton fb_guardarLibro;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton jb_ActualizarAcciones;
    private javax.swing.JButton jb_ActualizarEliminarLista;
    private javax.swing.JButton jb_ActualizarLista;
    private javax.swing.JButton jb_AgregarLibro;
    private javax.swing.JButton jb_BuscarLibro;
    private javax.swing.JButton jb_BuscarLibrosFav;
    private javax.swing.JButton jb_Eliminar;
    private javax.swing.JButton jb_MandarSolicitud;
    private javax.swing.JButton jb_cerrarSesion;
    private javax.swing.JButton jb_guardarUser;
    private javax.swing.JButton jb_iniciarsesion;
    private javax.swing.JPanel jp_AgregarLibros;
    private javax.swing.JPanel jp_Login;
    private javax.swing.JPanel jp_agregarUsuario;
    private javax.swing.JRadioButton rb_accion;
    private javax.swing.JRadioButton rb_fantasia;
    private javax.swing.JRadioButton rb_historia;
    private javax.swing.JRadioButton rb_romance;
    private javax.swing.JTextArea ta_DescripcionAmigo;
    private javax.swing.JTextArea ta_DescripcionDeUnLibro;
    private javax.swing.JTextArea ta_DescripcionTodosLibros;
    private javax.swing.JTextArea ta_Librosfav;
    private javax.swing.JTextArea ta_Listadeacciones;
    private javax.swing.JTextArea ta_descripcion;
    private javax.swing.JTextArea ta_libroseliminar;
    private javax.swing.JTextField tf_EliminarLibro;
    private javax.swing.JTextField tf_NombreCompleto;
    private javax.swing.JTextField tf_NombreLibro;
    private javax.swing.JTextField tf_NombreUsuario;
    private javax.swing.JTextField tf_NombreuserLogin;
    private javax.swing.JTextField tf_SolicitudNombre;
    private javax.swing.JTextField tf_autor;
    private javax.swing.JTextField tf_contraseña;
    private javax.swing.JTextField tf_contraseñaLogin;
    private javax.swing.JTextField tf_copias;
    private javax.swing.JTextField tf_correo;
    private javax.swing.JTextField tf_edicion;
    private javax.swing.JTextField tf_puntaje;
    private javax.swing.JTextField tf_quierobuscar;
    private javax.swing.JTextField tf_telefono;
    private javax.swing.JTextField tf_titulo;
    private javax.swing.JTextField tf_valor;
    // End of variables declaration//GEN-END:variables
    static ArrayList<Usuario> usuarios = new ArrayList();
    static ArrayList<Libro> libros = new ArrayList();
    static ArrayList Acciones = new ArrayList();
}
